format = """
$directory\
[](fg:#9A348E bg:#DA627D)\
$git_branch\
$git_state\
$git_status\
[](fg:#DA627D bg:#33658A)\
$time\
[ ](fg:#33658A)\
"""

# Inserts a blank line between shell prompts
add_newline = true

[directory]
style = "bg:#9A348E"
fish_style_pwd_dir_length = 1
format = "[ $path ]($style)"
truncation_symbol = "…/"

[git_branch]
symbol = ""
style = "bg:#DA627D"
format = '[ $symbol $branch ]($style)'

[git_status]
style = "bg:#DA627D"
format = "[$all_status$ahead_behind ]($style)"
modified = "✗"
ahead = "↑"
behind = "↓"
diverged = "⥄ "
up_to_date = "✓"
stashed = ""

[git_state]
style = "bg:#DA627D"

[time]
disabled = false
time_format = "%T" # Hour:Minute Format
style = "bg:#33658A"
format = '[ $time ]($style)'
