# vim: ft=conf
tap 'domt4/autoupdate'
tap 'homebrew/bundle'
tap 'homebrew/cask'
tap 'homebrew/cask-fonts'
tap 'homebrew/cask-versions'
tap 'homebrew/core'

brew 'autoconf'
brew 'bash'
brew 'bind'  # to get `dig` command
brew 'coreutils'
brew 'curl'
brew 'exa'
brew 'fd'
brew 'fish'
brew 'fzf'
brew 'gawk'
brew 'git'
brew 'gnu-sed'
brew 'grc'
brew 'grep'
brew 'ipython'
brew 'jq'
brew 'less'
brew 'lf'
brew 'neovim'
brew 'pwgen'
brew 'ripgrep'
brew 'rsync'
brew 'shfmt'
brew 'stow'
brew 'telnet'
brew 'tldr'
brew 'trash'
brew 'wget'
brew 'xh'

brew 'docker'
brew 'docker-compose'

brew 'corkscrew'
brew 'noti'
brew 'superbrothers/opener/opener'

brew 'ffmpeg'
brew 'youtube-dl'

brew 'golang'
brew 'npm'
brew 'python3'
brew 'ruby'
brew 'rust'

# nvimpager
brew 'scdoc'

# nvim null-ls
brew 'codespell'
brew 'luarocks'
brew 'shellcheck'

# Apps
cask 'alt-tab'
cask 'font-fira-code'
cask 'hiddenbar'
cask 'karabiner-elements'
cask 'kitty'
cask 'maccy'
cask 'macdown'
cask 'qbserve'
cask 'rectangle'
cask 'the-unarchiver'

# QuickLook plugins
#
# Do this to active these plugins after installing
#
# $ sudo xattr -cr ~/Library/QuickLook/*
# $ qlmanage -r
# $ qlmanage -r cache
# $ killall Finder
#
cask 'qlmarkdown'
cask 'qlstephen'

# Fonts
cask 'font-meslo-nerd-font'

# Mac App Store
mas 'Amphetamine', id: 937984704
mas 'Be Focus', id: 961632517
mas 'Fantastical', id: 975937182
