# vim: ft=conf
tap 'homebrew/bundle'
tap 'homebrew/cask'
tap 'homebrew/cask-fonts'
tap 'homebrew/cask-versions'
tap 'homebrew/core'
tap 'universal-ctags/universal-ctags'
tap 'domt4/autoupdate'

brew 'autoconf'
brew 'bash'
brew 'bat'
brew 'clipper'
brew 'coreutils'
brew 'cowsay'
brew 'ctop'
brew 'curl'
brew 'diff-so-fancy'
brew 'dive'
brew 'exa'
brew 'fd'
brew 'ffmpeg'
brew 'fish'
brew 'fzf'
brew 'gawk'
brew 'git'
brew 'gnu-sed'
brew 'gron'
brew 'hadolint'
brew 'helm'
brew 'httpie'
brew 'httpstat'
brew 'hyperkit'
brew 'imagemagick'
brew 'ipython'
brew 'java'
brew 'jq'
brew 'kubectl'
brew 'kubernetes-cli'
brew 'languagetool'
brew 'less'
brew 'lf'
brew 'libxml2'
brew 'lolcat'
brew 'luarocks'
brew 'mas'
brew 'minikube'
brew 'ncdu'
brew 'neovim', args: ['HEAD']
brew 'node'
brew 'noti'
brew 'openssl'
brew 'prettier'
brew 'pwgen'
brew 'python3'
brew 'ripgrep'
brew 'rsync'
brew 'shellcheck'
brew 'stow'
brew 'telnet'
brew 'terminal-notifier'
brew 'tldr'
brew 'tmux'
brew 'tokei'
brew 'trash'
brew 'txn2/tap/kubefwd'
brew 'universal-ctags/universal-ctags/universal-ctags', args: ['with-jansson', 'HEAD']
brew 'watch'
brew 'wget'
brew 'yarn'
brew 'youtube-dl'

# Apps
cask '1password'
cask 'docker'
cask 'hiddenbar'
cask 'hyperdock'
cask 'hyperswitch'
cask 'imageoptim'
cask 'iterm2'
cask 'karabiner-elements'
cask 'kitty'
cask 'maccy'
cask 'macdown'
cask 'qbserve'
cask 'telegram-desktop'
cask 'the-unarchiver'
cask 'unshaky'
cask 'vagrant'
cask 'workplace-chat'

# Fonts
cask 'font-meslo-nerd-font'

# Mac App Store
mas 'Amphetamine', id: 937984704
mas 'Be Focus', id: 961632517
mas 'Fantastical', id: 975937182
mas 'Keynote', id: 409183694
mas 'Numbers', id: 409203825
mas 'Spark', id: 1176895641
