# vim: ft=conf
tap 'Homebrew/homebrew-autoupdate'
tap 'homebrew/bundle'
tap 'homebrew/cask'
tap 'homebrew/cask-fonts'
tap 'homebrew/cask-versions'
tap 'homebrew/core'

# Apps
cask 'alt-tab'
cask 'font-fira-code'
cask 'hiddenbar'
cask 'karabiner-elements'
cask 'kitty'
cask 'maccy'
cask 'macdown'
cask 'menumeters'
cask 'qbserve'
cask 'rectangle'
cask 'the-unarchiver'
cask 'google-chrome'

# QuickLook plugins
#
# Do this to active these plugins after installing
#
# $ sudo xattr -cr ~/Library/QuickLook/*
# $ qlmanage -r
# $ qlmanage -r cache
# $ killall Finder
#
cask 'qlmarkdown'
cask 'qlstephen'

# Mac App Store
mas 'Amphetamine', id: 937984704
mas 'Be Focus', id: 961632517
mas 'Fantastical', id: 975937182

brew 'bash'
brew 'bind'  # to get `dig` command
brew 'coreutils'
brew 'curl'
brew 'exa'
brew 'fd'
brew 'fish'
brew 'fzf'
brew 'gawk'
brew 'git'
brew 'gnu-sed'
brew 'grc'
brew 'grep'
brew 'less'
brew 'lf'
brew 'neovim'
brew 'ripgrep'
brew 'rsync'
brew 'stow'
brew 'telnet'
brew 'trash'
brew 'wget'
brew 'xh'

brew 'corkscrew'
brew 'noti'
brew 'superbrothers/opener/opener'

brew 'ffmpeg'
brew 'youtube-dl'
