Vagrant.configure("2") do |config|
  config.vm.box = "bento/fedora-34"

  config.vm.provision "file", source: "~/.ssh/id_ed25519", destination: "/home/vagrant/.ssh/id_ed25519"
  config.vm.provision "file", source: "~/.ssh/id_ed25519.pub", destination: "/home/vagrant/.ssh/id_ed25519.pub"

  config.vm.synced_folder "../", "/home/vagrant/dotfiles/"

  config.vm.provision "shell", path: "../linux/bootstrap.sh", privileged: false

  config.vm.provider "virtualbox" do |v|
    v.name = "dev"
    v.memory = 2048
    v.cpus = 2
  end
end
