Vagrant.configure("2") do |config|
  config.vm.box = "bento/fedora-34"

  config.vm.synced_folder "../", "/home/vagrant/dotfiles/"
  config.vm.synced_folder "../../Downloads", "/home/vagrant/Downloads/"
  config.vm.synced_folder "../../Desktop", "/home/vagrant/Desktop/"
  config.vm.synced_folder "../../Music", "/home/vagrant/Music/"

  config.vm.provision "file", source: "~/.ssh/id_ed25519", destination: "/home/vagrant/.ssh/id_ed25519"
  config.vm.provision "file", source: "~/.ssh/conf.d/booking", destination: "/home/vagrant/.ssh/conf.d/booking"
  config.vm.provision "shell", path: "../linux/bootstrap.sh", privileged: false

  config.vm.network :forwarded_port, host: 3000, guest: 3000

  config.vm.provider "virtualbox" do |v|
    v.name = "dev"
    v.memory = 2048
    v.cpus = 2
  end
end
