FROM rust:latest

RUN apt-get update && \
  apt-get install -y --no-install-recommends  \
    build-essential musl-tools && \
  rm -rf /var/lib/apt/lists/*

RUN rustup target add x86_64-unknown-linux-musl

RUN cargo install --target x86_64-unknown-linux-musl xh
