version: "3"

services:
  fish:
    platform: linux/amd64
    build:
      context: .
      dockerfile: Dockerfile.fish
    volumes:
      - ./HOME/.local/bin:/out

  cargo:
    build:
      context: .
      dockerfile: Dockerfile.cargo
    volumes:
      - ./HOME/.local/bin:/out
