version: "3"

services:
  fish:
    build:
      context: .
      dockerfile: Dockerfile.fish
    volumes:
      - .local/bin:/out

  atop:
    build:
      context: .
      dockerfile: Dockerfile.atop
    volumes:
      - .local/bin:/out

  cargo:
    build:
      context: .
      dockerfile: Dockerfile.cargo
    volumes:
      - .local/bin:/out
