---
name: Benchmark
on:
  push:
    branches:
      - master

permissions:
  # deployments permission to deploy GitHub pages website
  deployments: write
  # contents permission to update benchmark contents in gh-pages branch
  contents: write

jobs:
  benchmark:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    env:
      OUTPUT_FILE: output.txt
      BRANCH_NAME: ${{ github.head_ref || github.ref_name }}
    steps:
      - uses: actions/checkout@v3

      - name: Install hyperfine
        run: |
          # yamllint disable rule:line-length
          curl -s https://api.github.com/repos/sharkdp/hyperfine/releases/latest \
          | jq -r '.assets[] | select(.name? | match("hyperfine-musl_.*_amd64.deb")) | .browser_download_url' \
          | wget -qi - -O hyperfine.deb
          sudo dpkg -i hyperfine.deb
          # yamllint enable rule:line-length

      - name: Run benchmark
        run: |
          TEMP_FILE=$(mktemp)

          hyperfine "$HOME/.asdf/shims/nvim --headless -c quitall" \
          --export-json "$TEMP_FILE" \
          --warmup 5 \
          --min-runs 15 \
          --show-output

          MEAN=$(jq .results[].mean < "$TEMP_FILE")

          cat <<EOF >"$OUTPUT_FILE"
          [
              {
                  "name": "Neovim startup time - Mean",
                  "unit": "Second",
                  "value": $MEAN
              }
          ]
          EOF

      - name: Upload benchmark
        uses: benchmark-action/github-action-benchmark@v1
        with:
          tool: customSmallerIsBetter
          output-file-path: ${{ env.OUTPUT_FILE }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          auto-push: true
          comment-on-alert: true
          fail-on-alert: true
          alert-threshold: '150%'
          alert-comment-cc-users: '@gametaro'
